name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
          python-version: '3.8'
          architecture: 'x64'
    - name: Configure pip caching
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: python -m pip install -r requirements/requirements.txt
    # - name: PyTest
    #   run: python -bb -Werror -m pytest -m 'not download'
    - name: Install flake8
      run: python -m pip install flake8
    - name: Tests Local with Bash
      env:
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        chmod +x ./test/test_local_picta.sh
        USER=$USER PASSWORD=$PASSWORD ./test/test_local_picta.sh
